import type { Metadata } from "next";
import "../globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { OrgProvider } from "@/contexts/organizationContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <SessionProvider>
    <OrgProvider>
      <SidebarProvider>
        <AppSidebar />
        <main className="flex-1 mx-3">
          <SidebarTrigger />
          {/* <ModeToggle /> */}
          {children}
        </main>
      </SidebarProvider>
    </OrgProvider>
    // </SessionProvider>
  );
}
